apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nagbot-deployment
spec:
  selector:
    matchLabels:
      app: nagbot
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nagbot
    spec:
      containers:
      - name: nagbot
        image: johnshew/nagbot
        ports:
        - containerPort: 8080
          name: restport
        - containerPort: 3978
          name: botport